#!/bin/bash

TOPDIR=$(pwd)

if [ ! $(basename `pwd`) = "fakestack" ]; then
	echo "source this file from its containing folder, please..."
	return 1
fi

# function to check if docker is running
function is_docker_up {
	local DOC_P
	DOC_P=$(ps -A | grep docker)
	if [ -z "$DOC_P" ]; then
		echo "WARNING: docker is not running..."
		echo "start it with:"
		echo "sudo service docker start"
		return 1
	fi

	return 0
}

# setting some aliases
alias ftools_runctrl="is_docker_up && docker run --privileged=true -ti -h controller --name=ctrl affear/ctrl:ok"
alias ftools_runcmp="is_docker_up && docker run --privileged=true -ti affear/cmp:ok"

# usefull functions
function ftools_build {
	local SHORT_NAME=$1
	local LONG_NAME

	if [ $# -eq 0 ]; then
		echo "Give short name, please."
		return 1
	fi

	if [ $SHORT_NAME = "ctrl" ]; then
		LONG_NAME="controller"
	elif [ $SHORT_NAME = "cmp" ]; then
		LONG_NAME="compute"
	else
		echo "Name must match 'ctrl' or 'cmp'"
		return 1
	fi

	if [ ! $(pwd) = "$TOPDIR/$LONG_NAME" ]; then
		echo "You must execute this script in $(basename $TOPDIR)/$LONG_NAME"
		return 1
	fi

	echo "Building affear/$SHORT_NAME:ok..."
	return is_docker_up && tar -czh . | docker build -t affear/$SHORT_NAME:ok -
}

function ftools_attach {
	if [ $# -eq 0 ]; then
		echo "Give container ID or name, please."
		return 1
	fi

	return is_docker_up && docker attach $1
}

function ftools_reinstall_nova {
	if [ $# -eq 0 ]; then
		echo "Give container ID or name, please."
		return 1
	fi

	return is_docker_up && docker exec $1 ./reinstall_service.sh nova
}

# everything is ok
return 0