#!/bin/bash
# sleeps are added because of strange behavior
# of screen on exit

function lil_pause {
	sleep 3
}

source fakerc
if [[ ! $? ]]; then
	echo "exiting"
	lil_pause
	exit 1
fi

N_CMP=$1
SHOW_STEP=5

echo "Before going on, please check to have a LIVE CONTROLLER INSTANCE."
read -r -p "Proceed in running compute nodes? [y/N] " response
if [[ $response =~ !([yY][eE][sS]|[yY])$ ]]; then
	echo "exiting..."
	lil_pause
	exit 1
fi

source scripts/helpers/functions
# Running one sample cmp
# (screen has already been configured in ftools_runcmps)
is_docker_up
if [[ ! $? ]]; then
	echo "Docker is down..."
	lil_pause
	exit 1
fi

echo "Running $N_CMP as daemons."
echo "docker ps to see status..."
echo "Or see samplecmp screen."
lil_pause

SCREEN_NAME="running"
screen_process samplecmp "docker run --privileged=true -ti affear/cmp:ok"

i=1
while [[ $i -lt $N_CMP ]]
do
	# running cmp as daemon! (-d option)
	is_docker_up
	if [[ ! $? ]]; then
		exit 1
	fi

	docker run --privileged=true -tid affear/cmp:ok

	if [[ $(($i % $SHOW_STEP)) ]]; then
		echo $i
	fi

	i=$(($i+1))
done

echo "All $N_CMP cmps are started... wait for stack.sh now"