#!/bin/bash

source fakerc
if [[ ! $? ]]; then
	echo "exiting"
	exit 1
fi

N_CMP=$1
SHOW_STEP=5

echo "Before going on, please check to have a LIVE CONTROLLER INSTANCE."
read -r -p "Proceed in running compute nodes? [y/N] " response
if [[ $response =~ !([yY][eE][sS]|[yY])$ ]]; then
	echo "you answered NO"
	exit 1
fi

source scripts/helpers/functions
# Running one sample cmp
# (screen has already been configured in ftools_runcmps)
if [[ ! $(is_docker_up) ]]; then
	exit 1
fi

echo "Running $N_CMP as daemons."
echo "docker ps to see status..."
echo "Or see samplecmp screen."

SCREEN_NAME="running"
screen_process samplecmp "docker run --privileged=true -ti affear/cmp:ok"

i=1
while [[ $i -lt $N_CMP ]]
do
	# running cmp as daemon! (-d option)
	if [[ ! $(is_docker_up) ]]; then
		exit 1
	fi

	docker run --privileged=true -tid affear/cmp:ok
	i=$(($i+1))

	if [[ $(($i % $SHOW_STEP)) ]]; then
		echo $i
	fi
done

echo "All $N_CMP cmps are started... wait for stack.sh now"