#!/bin/bash

source fakerc
if [[ ! $? ]]; then
	echo "exiting"
	exit 1
fi

# running controller
is_docker_up && docker run \
	--privileged=true \
	-ti \
	-h controller \
	--name=ctrl \
	--rm \
	-v $(pwd)/controller/local.conf:/devstack/local.conf \
	-v $(pwd)/shared/update_quotas.sh:/devstack/update_quotas.sh \
	affear/fakectrl:mydev