#!/bin/bash

if [ ! $(basename `pwd`) = "fakestack" ]; then
	echo "execute this script from project's topdir, please..."
	exit 1
fi

source scripts/helpers/functions
# Create a new named screen to run processes in
SCREEN_NAME="running"
configure_screen

# start all
screen_process cmps "scripts/helpers/run/cmps"