#!/bin/bash

if [ ! $(basename `pwd`) = "fakestack" ]; then
	echo "execute this script from project's topdir, please..."
	exit 1
fi

source scripts/helpers/functions
# Create a new named screen to run processes in
export SCREEN_NAME="updating"
if type -p screen > /dev/null && screen -ls | egrep -q "[0-9]\.$SCREEN_NAME"; then
	echo "$SCREEN_NAME already inited."
	echo "Delete it before proceding."
	exit 1
else
	configure_screen
fi

# start all
screen_process main "scripts/helpers/update/main"