#!/bin/bash
no_parallel=${1:-1}
t=$(date +"%m_%d_%Y__%H_%S")
default_label=$no_parallel'inparallel__'$t
label=${2:-$default_label}


echo "Spawning "$no_parallel" cmps..."
for i in $(seq 1 $no_parallel); do
	docker run \
	--privileged=true \
	-tid \
	-v $(pwd)/compute/local.conf:/devstack/local.conf \
	-v $(pwd)/shared/cmd.sh:/cmd.sh \
	affear/fakecmp:alpha
done