#!/bin/bash

if [ ! $(basename `pwd`) = "fakestack" ]; then
	echo "execute this script from project's topdir, please..."
	exit 1
fi

if [ $# -eq 0 ]; then
	echo "Specify the number of compute nodes you want to run, please"
	exit 1
fi

source scripts/helpers/functions
# Create a new named screen to run processes in
SCREEN_NAME="running"
if type -p screen > /dev/null && screen -ls | egrep -q "[0-9]\.$SCREEN_NAME"; then
	echo "$SCREEN_NAME already inited."
	echo "Using it."
else
	configure_screen
fi

# start cmps
screen_process cmps "scripts/helpers/run/cmps $1"