#!/bin/bash

source fakerc
if [[ ! $? ]]; then
	echo "exiting"
	exit 1
fi

is_docker_up
if [[ ! $? ]]; then
	echo "Docker is down..."
	exit 1
fi

# $1 is a cmp container ID
ftools_reinstall_nova $1
if [[ $? ]]; then
	echo "$1 updated SUCCESFULLY!"
else
	echo "$1 update FAILED!"
fi