#!/bin/bash

source fakerc
if [[ ! $? ]]; then
	echo "exiting"
	exit 1
fi

# create log directory
mkdir logs

echo "Updating controller node..."
CTRL=$(docker ps | awk '/ctrl/ {print $1}')

ftools_reinstall_nova $CTRL
if [[ ! $? ]]; then
	echo "CTRL not updated correctly, exiting..."
	exit 1
else
	echo "CTRL updated correctly!"
fi

# start compute nodes
echo "Updating compute nodes..."
CMPS=$(docker ps | awk '/cmp/ {print $1}')
NOW=$(date +"%y-%m-%d_%H-%M-%S")

i=0
N_CMP=${#CMPS[*]}
while [[ $i -lt $N_CMP ]]
do
	echo "--> updating $i"
	./scripts/helpers/update/cmp ${CMPS[$i]} > logs/${CMPS[$i]}.$NOW.log &
	i=$(($i+1))
done

i=0
while [[ $i -lt $N_CMP ]]
do
	wait -n
	if [[ $? ]]; then
		echo "--> $i updated succesfully!"
	else
		echo "--> $i updated FAILED."
	fi
	i=$(($i+1))
done

echo "ENDED."
echo "For logs, check logs directory."